### ISSUE TITLE
Problem compiling okhttp library

### ISSUE THREAD

**Issue by khirr** [TGIO/ParseLiveQuery#1]
Hello,
Thanks for this powerful and beautiful library.

I've found a error when compile using your library, the error says:
Could not find com.squareup.okhttp3:okhttp-ws:3.4.0-SNAPSHOT

I've downloaded your library and change for:
compile 'com.squareup.okhttp3:okhttp-ws:3.4.1'

And now it works.

**Comment by TGIO** [comment]
thx mate!
