### ISSUE TITLE
Receive objects with ACL

### ISSUE THREAD

**Issue by khirr** [TGIO/ParseLiveQuery#2]
Hello,
I've been trying the library and it works perfect but, when I have Message with ACL the event never is triggered so I think is necessary send authToken: https://github.com/ParsePlatform/parse-server/wiki/Parse-LiveQuery-Protocol-Specification

I see it's a optional element, is possible to send this optional field?

Thank you.

**Comment by TGIO** [comment]
do you mean 'sessionToken' ?

**Comment by khirr** [comment]
Yes, sorry.
