### ISSUE TITLE
Unsubscribe and Other Query options

### ISSUE THREAD

**Issue by LuizEdgar** [TGIO/ParseLiveQuery#3]
Hello, TGIO!

First of all, thank you for your amazing work with LiveQuery!! :)

I'd like to ask you a few things.
1. I'd like to know if I have a unsubscribe option. In case of negative, do you know how a unsubscribed query would affect the server?
2. In my project I have to use other queries parts different then whereEqual. How can I use things like whereKeyExists("attrs"), for example?

Thank you TGIO! :)

**Comment by TGIO** [comment]
@LuizEdgar Hi
1. No idea yet, need to research / test it.
2. Query thingies will be improved soon.

**Comment by khirr** [comment]
Hi, I've been checking PLQ [documentation](https://github.com/ParsePlatform/parse-server/wiki/Parse-LiveQuery-Protocol-Specification)  and to unsubscribe just need tu send requestId of the current query and "op": "unsubscribe", I suggest make BaseQuery.requestId public to can use it to unsubscribe or create a method for LiveQueryClient to "unsubscribe" and pass your BaseQuery.
