### ISSUE TITLE
What is WS_URL and MY_APP_ID?

### ISSUE THREAD

**Issue by tran-huy-phuc** [TGIO/ParseLiveQuery#5]
Hi @TGIO 
I am looking at your sample. 
As the title said, can you explain me ?

**Comment by TGIO** [comment]
Hi @thphuc 

MY_APP_ID - is an application id. [see example](https://github.com/TGIO/ParseLiveQuery/blob/master/Server/server.js#L9)

WS_URL - is the url forwebsocket, for example "ws:/" + server_adress + ":4040/"

all clear ?

**Comment by tran-huy-phuc** [comment]
Hi @TGIO 
Thanks for your quickly reply.
I understand app id, but I still don't get how to setup and get WS_URL. Can you give me instruction?

**Comment by TGIO** [comment]
it's just web socket url for ur server. 
for example, u have parse server url "http://myserver.com/parse"
Use "ws" instead of "http"or "https" and just add port "4040" for example.

ur WS_URL is now "ws://myserver.com:4040/". But this may vary depending on ur server configuration

**Comment by tran-huy-phuc** [comment]
My server url is "http://xyz.com:1337/parse". 
So what is the ws url in my case? 
Port 4040 is default port? (Also, I am using port 4040 for parse dashboard)
If I want to change this port, how should I do?

Thanks!

**Comment by tran-huy-phuc** [comment]
I got this working so I can close this.
