### ISSUE TITLE
Exception: NullPointerException: value == null

### ISSUE THREAD

**Issue by tran-huy-phuc** [TGIO/ParseLiveQuery#6]
Hi @TGIO,

I tried to add parse live query to my project. I got below issue:
1. I added the library to gradle file, run the app. Every time I save an object to parse-server, I got NullPointerException: value == null.
2. I thought that is because I didn't setup WS URL and APP ID. Then I setup them,  I think I did correctly because I got below log when running the app:
   
   > {"op":"connected","clientId":6}
   > {"op":"subscribed","clientId":6,"requestId":1}
   > {"op":"subscribed","clientId":6,"requestId":1}

But again, every time I save an object to parse-server, I got NullPointerException: value == null.

So my conclusion: This issue started happening from I add the library to gradle. Do you have any idea?

(I am using parse-server 2.2.17)

**Comment by TGIO** [comment]
Hi @thphuc 

Just replicate config from server example. Make sure u set up livequery on server correctly.
Also stacktrace will help me to find out what's wrong with it.

**Comment by emadehsan** [comment]
Oddly enough, had the same problem but adding Parse Client key solved the issue.

```
    Parse.initialize(new Parse.Configuration.Builder(context)
            .applicationId(PARSE_APP_ID)
            .clientKey("")  // if not setup on server, initialize with empty string like ""
            .server(PARSE_SERVER_URL)
            .build()
```

**Comment by tran-huy-phuc** [comment]
Thanks @emadehsan It works!
