### ISSUE TITLE
What is the WS_URL and where can I get if from?

### ISSUE THREAD

**Issue by zouzoux** [TGIO/ParseLiveQuery#7]
I tried to put my parse server url but nothing is happening....
I am hosting my parse server on heroku

**Comment by TGIO** [comment]
WS stands for WebSocket. Im not sure if heroku supports LiveQuery yet. 
for example "ws://address:port/";

**Comment by zouzoux** [comment]
I was able to set LiveQuery on heroku with the iOS version, do you  think there is a way to do it with heroku on android version? `do you know where can I get my ws url?

**Comment by zouzoux** [comment]
It worked! Replaced https of my parse server url with ws!
